### ISSUE TITLE
2nd button results in blank page on Chrome and Edge mobile

### ISSUE THREAD

**Issue by rbeesley** [Shamus03/ralc#6]
It seems like everything else works well and installed as a PWA nicely.

**Comment by Shamus03** [comment]
Nice catch!  I'll look into this some time this evening, or if you know the issue I'd welcome a PR.

**Comment by rbeesley** [comment]
I glanced through the code and nothing stood out. I couldn't figure out how to get the extra keys either.

**Comment by Shamus03** [comment]
> I couldn't figure out how to get the extra keys either.

They'll appear if you rotate your device to landscape (or on desktop, resize the window to a landscape aspect ratio).

**Comment by rbeesley** [comment]
Fixed
