### ISSUE TITLE
Support for international keyboards

### ISSUE THREAD

**Issue by mhoene** [Shamus03/ralc#8]
Many thanks for this terrific tool! For me, and for many other international users, it would be even more useful if it supported international keyboard layouts. Would that be possible?

At this point, the operator keys '+', '-', '/' etc. appear to be hardcoded to where they are located on a US keyboard. I for one am using a German keyboard (https://en.wikipedia.org/wiki/German_keyboard_layout#/media/File:KB_Germany.svg), where those keys are placed differently, and where I have to press, for example, '(' to get '*'.

Can the keys be picked up "semantically" rather than by their position?

**Comment by Shamus03** [comment]
Hey, thanks for your feedback!

I would love to support international layouts - I think I just need to change the event listeners (like the one on [this line](https://github.com/Shamus03/ralc/blob/3aecf47860ad92a49326bb60f2d9c5b75aac2e36/src/App.tsx#L563)) to use the correct symbols instead of "Shift+Digit8" (for multiply).  I will test this and possibly add a fix.

**Comment by Shamus03** [comment]
@mhoene I just pushed a fix for this, please let me know if this doesn't solve the issue!

**Comment by mhoene** [comment]
Hi @Shamus03, thank you so much for the lightning quick fix! It almost all works :-)

There is one issue I see with my keyboard layout: "Slash" appears to pick up the key where the slash is on the US keyboard -- the one left of the right shift key --, not the '/'. When I push that key (labeled '-' here), it triggers both opDivide and opSubtract.

I believe the fix might be to just change 'Slash' in [this line](https://github.com/Shamus03/ralc/blob/dfc444438547d929be911ec1d506e5966d7bc356/src/App.tsx#L560) to '/':
          <CalculatorButton action={opDivide} shortcuts={['NumpadDivide', '/']} primary>÷</CalculatorButton>

Also, '^' isn't picked up in [line 556](https://github.com/Shamus03/ralc/blob/dfc444438547d929be911ec1d506e5966d7bc356/src/App.tsx#L556). I'm not sure how to fix that, or whether it is easily fixable at all. On the German keyboard, '^' is a special key which modifies subsequent vowels (e.g., 'â') and doesn't get triggered on its own. If I want a '^' character, I have to press the key twice, causing '^^' to appear, and delete one...

**Comment by Shamus03** [comment]
Sorry I took a while to get to this.  The slash issue fix is building now.

For the carat, feel free to open a separate issue - but I probably won't fix it myself.  I would happily accept a pull request from anyone who would like to work on it.
